
language: node_js
node_js: "7"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx
  - linux

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - npm run test && npm run lint
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then \
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build; fi \
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build -- --mac --win; fi \
    fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Максим Ильин"
  - git config --local user.email "negamaxi@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

before_deploy: ls -la dist/

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: dist/*.dmg
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
